# Generated by Django 5.2 on 2025-12-27 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('rtsp_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_confidence_threshold', models.FloatField(default=0.5, help_text='Minimum confidence for violation detection')),
                ('helmet_detection_enabled', models.BooleanField(default=True)),
                ('plate_detection_enabled', models.BooleanField(default=True)),
                ('frame_skip', models.IntegerField(default=5, help_text='Process every Nth frame')),
                ('max_violations_per_minute', models.IntegerField(default=10, help_text='Rate limiting')),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('frames_processed', models.IntegerField(default=0)),
                ('violations_detected', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('NO_HELMET', 'No Helmet'), ('NO_PLATE', 'No Number Plate'), ('BOTH', 'No Helmet and No Plate')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('OTHER', 'Other')], max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(help_text='AI confidence level (0-1)')),
                ('image', models.ImageField(upload_to='violations/%Y/%m/%d/')),
                ('annotated_image', models.ImageField(blank=True, upload_to='violations/annotated/%Y/%m/%d/')),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed'), ('FALSE_POSITIVE', 'False Positive'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='detector.camera')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='detector_vi_detecte_4b96b6_idx'), models.Index(fields=['status'], name='detector_vi_status_fd7291_idx'), models.Index(fields=['violation_type'], name='detector_vi_violati_a9813f_idx')],
            },
        ),
    ]
